[client]
showErrorDetails = false

[logger]
level = "warning"

[theme]
primaryColor = "#0f4c81"
backgroundColor = "#f4f7fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#233047"
font = "sans serif"
